# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dd53d023cc5fab0bdc90699357a67bd92969b157f4529c4520372134bb0a8e24b2f320ed21296a686b7d9a5249851465b1f1136a292699cd90557abe35d18e0

test:
  secret_key_base: e228e93e007663530dbad9a6f6be30e9c19f641fe306a320e0ecdcedd8ad72897ec8b9d6fc0ca21337893c5b6ef1d494b7a73c63a1df422b4acc1c4b585891d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
